name: laza_commerce
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  kartal: ^3.5.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  get_it: ^7.6.7
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  path: ^1.9.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Icons/

