// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uhLZbnluu6VvH_93j1IiBEpSbT8Q6t8',
    appId: '1:1092153259217:web:4923cd645e7fca5d3141f0',
    messagingSenderId: '1092153259217',
    projectId: 'laza-commerce',
    authDomain: 'laza-commerce.firebaseapp.com',
    storageBucket: 'laza-commerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mpvzNmLvuN8nONEmMeF4xAjzuCl1a88',
    appId: '1:1092153259217:android:9a140f59d16109ab3141f0',
    messagingSenderId: '1092153259217',
    projectId: 'laza-commerce',
    storageBucket: 'laza-commerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs9USKbXQUIfYFxNoyRf8p98cHdKi0vVQ',
    appId: '1:1092153259217:ios:f246f885d104ab0f3141f0',
    messagingSenderId: '1092153259217',
    projectId: 'laza-commerce',
    storageBucket: 'laza-commerce.appspot.com',
    iosBundleId: 'com.example.lazaCommerce',
  );
}
